#!/bin/bash -e

TMP_DIR=$(mktemp -d)
cd $TMP_DIR

wget http://mirrors.ibiblio.org/gnu/ftp/gnu/stow/stow-2.3.1.tar.gz
tar xf stow-2.3.1.tar.gz
cd stow-2.3.1
./configure --prefix=$HOME/.local
make install
