#!/bin/bash -e

SCRIPT_DIR=$(dirname $(realpath $0))
VERSION=2.3.1

if command -v stow &> /dev/null; then
    echo "stow is already installed, check version"
    version=$(stow -V | grep -oP 'version \K.*')
    if [ $version = $VERSION ]; then
       echo "version $version match, exits"
       exit 0
    fi
fi

TMP_DIR=$(mktemp -d)
cd $TMP_DIR

wget https://ftp.gnu.org/gnu/stow/stow-2.3.1.tar.gz
tar xf stow-2.3.1.tar.gz
cd stow-2.3.1
./configure --prefix=$HOME/.local
make install
