#!/bin/bash

TMP_DIR=$(mktemp -d)
cd $TMP_DIR

URL=https://github.com/ogham/exa/releases/download/v0.9.0/exa-linux-x86_64-0.9.0.zip
FILE=$(basename $URL)
DIR=${FILE%.*}

wget $URL
unzip $FILE
cp exa-linux-x86_64 $HOME/.local/bin/exa