#!/bin/bash -e
if ! command -v asdf &> /dev/null
then
    echo "asdf could not be found"
    exit -1
fi
sudo apt install -y --no-install-recommends make build-essential libssl-dev zlib1g-dev libbz2-dev libreadline-dev libsqlite3-dev wget curl llvm libncurses5-dev xz-utils tk-dev libxml2-dev libxmlsec1-dev libffi-dev liblzma-dev
asdf plugin-add python
asdf install python 3.9.0
asdf global python 3.9.0 system