#!/bin/bash

COMMAND=rg

if command -v $COMMAND &> /dev/null; then
    echo "$COMMAND is already installed, check version"
    exit 0
fi

TMP_DIR=$(mktemp -d)
cd $TMP_DIR

URL=https://github.com/BurntSushi/ripgrep/releases/download/12.1.1/ripgrep-12.1.1-x86_64-unknown-linux-musl.tar.gz
FILE=$(basename $URL)
DIR=${FILE%.*}

wget $URL
tar xf $FILE --strip-components=1
cp rg $HOME/.local/bin/rg
