#!/bin/bash -e

SCRIPT_DIR=$(dirname $(realpath $0))
COMMAND=unison
VERSION=2.51.3

if command -v $COMMAND &> /dev/null; then
    echo "$COMMAND is already installed, check version"
    exit 0
    # version=$(tmux -V | grep -oP 'tmux \K.*')
    # if [ $version = $VERSION ]; then
    #     echo "version $version match, exits"
    #     exit 0
    # fi
fi

TMP_DIR=$(mktemp -d)
cd $TMP_DIR

URL=https://github.com/bcpierce00/unison/releases/download/v2.51.3/unison-v2.51.3+ocaml-4.11.1+x86_64.linux.tar.gz
FILE=$(basename $URL)

wget $URL
tar xf $FILE
cp -r bin/* $HOME/.local/bin

# setup shared dir
mkdir -p $HOME/unison_shared
mkdir -p $HOME/unison_backup
