#!/bin/bash

SCRIPT_DIR=$(dirname $(realpath $0))

sudo apt install -y --no-install-recommends \
     highlight fd-find unzip neovim direnv

$SCRIPT_DIR/install_asdf
$SCRIPT_DIR/install_stow
$SCIRPT_DIR/install_tmux
$SCRIPT_DIR/install_exa
$SCRIPT_DIR/install_rg
$SCRIPT_DIR/install_unison
