#!/bin/bash -e

SCRIPT_DIR=$(dirname $(realpath $0))
COMMAND=tmux
VERSION=3.1c

if command -v $COMMAND &> /dev/null; then
    echo "$COMMAND is already installed, check version"
    version=$(tmux -V | grep -oP 'tmux \K.*')
    if [ $version = $VERSION ]; then
        echo "version $version match, exits"
        exit 0
    fi
fi

sudo apt install -y --no-install-recommends libevent-dev ncurses-dev build-essential bison pkg-config

TMP_DIR=$(mktemp -d)
cd $TMP_DIR

JOBS=$(($(nproc)/2))

wget https://github.com/tmux/tmux/releases/download/3.1c/tmux-3.1c.tar.gz
tar xf tmux-3.1c.tar.gz
cd tmux-3.1c
./configure --prefix=$HOME/.local
make install -j $JOBS
