#!/bin/bash

SCRIPT_DIR=$(dirname $(realpath $0))

pkg_list=(
    curl
    highlight
    fd-find
    unzip
    neovim
    direnv
    xdg-utils
    xclip
    xsel
    docker.io
    zsh
    ruby
    htop
    jq
    trash-cli
)


# workaround for missing package because of different ubuntu version
for pkg in "${pkg_list[@]}";
do
    sudo apt install -y --no-install-recommends $pkg
done

$SCRIPT_DIR/install_asdf
$SCRIPT_DIR/install_stow
$SCRIPT_DIR/install_tmux
$SCRIPT_DIR/install_exa
$SCRIPT_DIR/install_rg
$SCRIPT_DIR/install_unison
$SCRIPT_DIR/install_rmtrash

hash -r
$SCRIPT_DIR/install_asdf_python
